// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fullstackbe.Gateways.Dal;

#nullable disable

namespace fullstackbe.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("fullstackbe.Gateways.Dal.VirksomhedDao", b =>
                {
                    b.Property<int>("Cvr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("By")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Postnummer")
                        .HasColumnType("INTEGER");

                    b.HasKey("Cvr")
                        .HasName("VirksomhedCvr_PK");

                    b.ToTable("Virksomheds");
                });
#pragma warning restore 612, 618
        }
    }
}
